# Generated by Django 5.2.6 on 2025-09-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_mahasiswa_nim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
