# Generated by Django 5.2.7 on 2025-10-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drfpost',
            options={'ordering': ['-uploaded']},
        ),
        migrations.AlterField(
            model_name='drfpost',
            name='rating',
            field=models.CharField(choices=[(1, 'excellent'), (0, 'average'), (-1, 'bad')], default='average', max_length=10),
        ),
    ]
