# Generated by Django 5.2.7 on 2025-10-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRFPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('excellent', 1), (0, 'average'), ('bad', -1)], default='average', max_length=10)),
            ],
        ),
    ]
