# Generated by Django 5.2.7 on 2025-10-16 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0002_alter_drfpost_options_alter_drfpost_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('prodi', models.CharField(choices=[('manajemen', 'S1 Business / Manajemen'), ('marketing', 'S1 Branding / Marketing'), ('finance', 'S1 Finance & Banking'), ('fintech', 'S1 Financial Technology'), ('accounting', 'S1 Accounting / Akuntansi'), ('ekonomi_bisnis', 'S1 Business Economics / Ekonomi Bisnis'), ('hospitality', 'S1 Hospitality & Tourism Management'), ('event', 'S1 Event Management / MICE'), ('hukum_bisnis', 'S1 Business Law / Hukum Bisnis'), ('teknik_komputer', 'S1 Computer Systems Engineering'), ('software_engineering', 'S1 Software Engineering'), ('teknologi_pangan', 'S1 Food Business Technology'), ('energi_terbarukan', 'S1 Renewable Energy Engineering'), ('desain_produk', 'S1 Product Design Engineering'), ('matematika_bisnis', 'S1 Business Mathematics')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='drfpost',
            name='rating',
            field=models.CharField(choices=[(1, 'excellent'), (0, 'average'), ('bad', -1)], default='average', max_length=10),
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to='basic_api.dosen')),
            ],
            options={
                'verbose_name_plural': 'Mahasiswa',
            },
        ),
    ]
