# Generated by Django 5.2.8 on 2025-11-07 09:19

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('kode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Jurusan',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('MAHASISWA', 'Mahasiswa'), ('DOSEN', 'Dosen')], default='MAHASISWA', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.jurusan', verbose_name='Jurusan')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Matakuliah',
            fields=[
                ('kode_mk', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nama_mk', models.CharField(max_length=150)),
                ('sks', models.IntegerField(default=3)),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matakuliah_set', to='users.jurusan')),
                ('pengajar', models.ManyToManyField(blank=True, limit_choices_to={'role': 'DOSEN'}, related_name='matakuliah_diajar', to=settings.AUTH_USER_MODEL, verbose_name='Dosen Pengajar')),
            ],
            options={
                'verbose_name_plural': 'Mata Kuliah',
            },
        ),
        migrations.CreateModel(
            name='KomponenNilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_komponen', models.CharField(choices=[('UTS', 'Ujian Tengah Semester'), ('UAS', 'Ujian Akhir Semester'), ('Tugas', 'Tugas/Proyek'), ('Kehadiran', 'Kehadiran'), ('Lainnya', 'Lainnya')], max_length=50)),
                ('bobot_persen', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bobot dalam persen (misal: 30.00)', max_digits=5)),
                ('matakuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komponen_set', to='users.matakuliah')),
            ],
            options={
                'verbose_name_plural': 'Komponen Penilaian',
                'unique_together': {('matakuliah', 'nama_komponen')},
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_angka', models.DecimalField(decimal_places=2, help_text='Nilai mentah (0-100)', max_digits=5)),
                ('mahasiswa', models.ForeignKey(limit_choices_to={'role': 'MAHASISWA'}, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to=settings.AUTH_USER_MODEL)),
                ('komponen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.komponennilai')),
            ],
            options={
                'verbose_name_plural': 'Assessment Scores',
                'unique_together': {('mahasiswa', 'komponen')},
            },
        ),
        migrations.CreateModel(
            name='NilaiAkhir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_total', models.DecimalField(blank=True, decimal_places=2, help_text='Nilai akhir terbobot (0-100)', max_digits=5, null=True)),
                ('nilai_huruf', models.CharField(blank=True, choices=[('A', 'A'), ('AB', 'AB'), ('B', 'B'), ('BC', 'BC'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2, null=True)),
                ('mahasiswa', models.ForeignKey(limit_choices_to={'role': 'MAHASISWA'}, on_delete=django.db.models.deletion.CASCADE, related_name='transkrip', to=settings.AUTH_USER_MODEL)),
                ('matakuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.matakuliah')),
            ],
            options={
                'verbose_name_plural': 'Nilai Akhir (Transkrip)',
                'unique_together': {('mahasiswa', 'matakuliah')},
            },
        ),
    ]
