# Generated by Django 5.2.6 on 2025-09-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
