# Generated by Django 5.2.6 on 2025-09-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_mahasiswa_nim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
