# Generated by Django 5.2.6 on 2025-09-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_mahasiswa_nim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.PositiveIntegerField(db_index=True, default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
